### ISSUE TITLE
Opción de verificar identidad no debería aparecer

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/miciudad2#11]
**Comportamiento esperado:**

Que ofrezca verificación automática solamente

**Comportamiento observado:**

Ofrece por "correo postal" lo que no tiene sentido y confunde en nuestro caso

**Pasos para reproducirlo:**
1. Crear el usuario
2. Ingresar por primera vez
3. Aparecerán las opciones de verificación. Se adjunta captura:

![deshabilitar-metodo-que-no-usaremos](https://user-images.githubusercontent.com/463429/40373643-5730aada-5db5-11e8-9755-97943172c818.png)

**Comment by diegocrzt** [comment]
En el PR #14 se fuerza a que la siguiente página luego de la verifiación sea la página principal.

**Comment by lupa18** [comment]
Confirmado que no aparece más. Cierro.
