### ISSUE TITLE
Al crear nueva iniciativa solo ofrece 1 opción cuando en realidad hay 4 

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/miciudad2#13]
**Comportamiento esperado:**

Que ofrezca todos los tipos creados previamente

**Comportamiento observado:**

Solo ofrece 1 tipo de iniciativa, en este caso "Tipo de iniciativa" (ver captura abajo)

**Pasos para reproducirlo:**

**1.** Ir a la creación de iniciativa

**2.** En el primer paso ofrecerá "tipo":

![seleccion_530](https://user-images.githubusercontent.com/463429/40374253-b33b9dde-5db6-11e8-87b7-0170ae9b97bb.png)

**3.** En la parte administrativa se observan 4:

![seleccion_529](https://user-images.githubusercontent.com/463429/40374294-c5a09ff6-5db6-11e8-911e-0343acbe943b.png)

**Comment by diegocrzt** [comment]
Esto es así en decidim hoy día por que un **tipo de iniciativa** debe estar asociado por lo menos a un **Ámbito** para hacer esta asociación, luego de crear el tipo de iniciativa 

1. Seleccionar la iniciativa para editarla

![20180522210434_m4800](https://user-images.githubusercontent.com/6553005/40398055-fd83d760-5e03-11e8-8978-4537b11f2ada.png)

2. En la parte inferior del formulario buscar el apartado **Ámbitos para el tipo de iniciativa** e ir al botón **Nuevo/a**

![20180522210452_m4800](https://user-images.githubusercontent.com/6553005/40398106-409672ba-5e04-11e8-9e07-c65437cb32aa.png)

3. Elegir el Alcance y la cantidad de soportes requeridos (votos o apoyo) e ir al botón **Crear**

![20180522210530_m4800](https://user-images.githubusercontent.com/6553005/40398163-8b674ad0-5e04-11e8-928d-f2f6f41e48f3.png)

4. De esta manera el usuario puede ver dichos Tipos de iniciativa en el asistente de creación de iniciativas

![20180522211152_m4800](https://user-images.githubusercontent.com/6553005/40398214-c36fd762-5e04-11e8-8d2e-6399aa1cc7d3.png)

**OBS** Los Ámbitos ya deben existir previamente, y se pueden crear **Tablero administrativo**, apartado de **Configuración** > **Ámbitos**

**Comment by lupa18** [comment]
Bien. Cierro entonces. Para constancia dejo documentado acá, que **ámbito** es una traducción de **scope** que en realidad es **alcance** y tiene que ver con el **territorio**. Así lo dice el manual: 

> To finish configuring the platform you will need to specify the areas, that is, the 
territorial organisation (districts, neighbourhoods, etc.,) and/or sectoral areas that 
the participatory processes can be linked to. The areas can be classed according to 
scopes ​ where appropriate. 
> To configure scope types, go to the ​ SETTINGS​ , submenu click on ​ Scope types and 
then click on ​ ADD​ . Fill in the fields ​ Name and ​ Plural ​ (in Catalan and in Spanish) and 
click on ​ Create scope type​ (Figure 11). 

Además al parecer "Tipo de ámbito" no es obligatorio, por lo que será mejor no usarlo.
