### ISSUE TITLE
Imposible editar o ver iniciativas

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/miciudad2#15]
**Comportamiento esperado:**

Editar una iniciativa ó

Ver las iniciativas en https://beta.encarnacion.org.py/initiatives

**Comportamiento observado:**

Error: Ha habido un problema con nuestro servidor

**Pasos para reproducirlo:**

Es **probable** que se deba a que borré todos los ámbitos y creé uno nuevo llamado "Municipal". Si es esto, parece un poco grave que al borrar los ámbitos no se advierta o no se actualice la base quedando en este estado inconsistente. 

O puede que se deba a otra cosa.

**Comment by diegocrzt** [comment]
SI efectivamente al borrar los ambitos no se valida que se quede consistente la base de datos, hay que evaluar esto, es un bug complicado por que implica validar modulos de componentes diferentes el core e iniciativas o reclamos inclusive

**Comment by yank07** [comment]
Se reporto el bug en el repo de Decidim.

**Comment by lupa18** [comment]
Dejo abierto para seguimiento y coloco en el milestone 1.1
