### ISSUE TITLE
Texto no se ve al confirmar ser parte de la comisión

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/miciudad2#27]
**Comportamiento esperado:**

Leer los detalles de confirmación de ser parte de la comisión en una iniciativa

**Comportamiento observado:**

No se puede leer título, ni autor ni parte de la descripción. Se adjunta captura: 

![seleccion_552](https://user-images.githubusercontent.com/463429/40811805-bba83e04-6500-11e8-8833-c2d828423a44.png)

Se probó con Firefox 60.0.1 y Chrome 67.0.3396.62

**Pasos para reproducirlo:**
1. Crear una iniciativa y copiar el enlace que brinda para ser parte de la comisión
2. Desde otro navegador/computador recibir y acceder a ese enlace haciendo clic

**Comment by diegocrzt** [comment]
Con el cambio en #28, se puede comprobar que el mensaje de confirmación para creación de comité se muestra adecuadamente

![20180601121510_m4800](https://user-images.githubusercontent.com/6553005/40851511-a011438a-6595-11e8-9c6a-dc5a058c9e06.png)

**Comment by yank07** [comment]
Listo, este tema se dio por el cambio del menu a position: absolute. Las paginas que tengan el mismo problema deberian tener un margin-top mas grande para solucionar el inconveniente
