### ISSUE TITLE
Error al cambiar un enlace en portada

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/miciudad2#3]
**Comportamiento esperado:** Coloco una nueva URL en un botón de portada y al guardar se efectúa el cambio. 

**Comportamiento observado:** No permite guardar el cambio y dice: "Se produjo un error al actualizar esta organización" y se eliminan todas las imágenes que ya existían en el formulario, así que quedo trancado. 

**Pasos para reproducirlo:** 
1. Con el admin de la organización ir a "Configuración" y luego "Apariencia"
2. Ir a la sección "Banner de contenido resaltado"
3. Modificar la URL
4. Dar clic en Actualizar (abajo al final)

**Comment by diegocrzt** [comment]
Se puede probar editar la apariencia y la URL concretamente, 
https://beta.encarnacion.org.py/admin/organization/appearance/edit

**Comment by lupa18** [comment]
Quedó
