### ISSUE TITLE
[404] Términos y condiciones 

### ISSUE THREAD

**Issue by diegocrzt** [TEDICpy/miciudad2#32]
En la página de registrar usuario, al hacer click en términos y condiciones lanza un 404

https://beta.encarnacion.org.py/pages/terms-and-conditions

**Comment by lupa18** [comment]
La página existe y esta es su URL: https://beta.encarnacion.org.py/pages/terminos-y-condiciones

**Comment by diegocrzt** [comment]
si, existen páginas y referencias en el core de decidim que apuntan al link viejo(terms-and-conditions), habrá que sobreescribir esas partes

**Comment by lupa18** [comment]
No se puede establecer algún sistema de alias o similar?

**Comment by diegocrzt** [comment]
Se corrigió el error encontrado, se puede  volver a probar

**Comment by lupa18** [comment]
Para volver a probar necesitaría tener una URL del "perfil de usuario" donde fallaba, pues en este issue hay una URL destino 404 pero no queda claro desde donde se llamaba.

**Comment by diegocrzt** [comment]
### Pasos para probar el bug encontrado
La URL es https://beta.encarnacion.org.py/users/sign_up que corresponde a la pantalla de registrar usuario. Requiere que se cierre la sesión actual si hay alguna.

#### Click en Regístrate
![20180713111805_m4800](https://user-images.githubusercontent.com/6553005/42699437-c09958ee-868e-11e8-9fb0-c5f177dfe6d8.png)

#### En la parte inferior de la vista click en el enlace de "los términos y condiciones de uso."

![20180713111814_m4800](https://user-images.githubusercontent.com/6553005/42699474-de971480-868e-11e8-907e-5e7da848d63d.png)

#### Debería verse la vista de los términos y condiciones

![20180713111822_m4800](https://user-images.githubusercontent.com/6553005/42699491-ef7677d2-868e-11e8-83fb-1fca8aac9892.png)
