### ISSUE TITLE
Páginas estáticas no creadas

### ISSUE THREAD

**Issue by diegocrzt** [TEDICpy/miciudad2#33]
Algunas páginas estáticas deben estar creadas para explicar el funcionamiento de ciertas características como denuncias, iniciativas, eventos. Actualmente algunos enlaces no están definidos: ej

https://beta.encarnacion.org.py/pages/denuncias
https://beta.encarnacion.org.py/pages/initiatives

**Comment by lupa18** [comment]
acordate que denuncias se llama reportes ahora
y deberíamos de ver la forma de llamarle iniciativas en vez de initiatives (si es muy complicado lo dejamos para versión futura)

**Comment by diegocrzt** [comment]
Si, este asunto por raro que parezca es algo complejo, 

**TL;DR** tomará tiempo hacer refactor de todo y cuidar los revisar que el inflector no falle en alguna parte.

**En detalle**
En rails se usa [inflection](http://api.rubyonrails.org/classes/ActiveSupport/Inflector/Inflections.html)  para generar la forma plural o singular de una palabra, esto a su vez se usa para inferir los nombres de métodos, tablas y urls automáticamente. 
Este mecanismo funciona bien en inglés y aunque ya está desarrollado para el castellano y otros idiomas, existen casos donde fallá, ya ocurrió con el modulo de denuncias justamente, que fue originalmente hecho usando la palabra castellano **denuncia** y su forma plural **denuncias**. 
Para el caso de denuncias evite cambiar las partes internas del código por esta razón (entre ellas en generador de urls)
Para el caso de eventos, sucede lo mismo. 
En ambos casos el cambio es posible pero requiere hacer refactor de todo el código y volver a probar todo por si el inflector falle en algún caso especial. ej: una url que se genere mal.

**Comment by lupa18** [comment]
Listo, cambiado para 1.1
Igual me es muy extraño que identificado el fallo no se pueda arreglar nomás en inflection directamente.

**Comment by lupa18** [comment]
Seguimos en las tareas específicas de corrección de URLs en 1.1
