### ISSUE TITLE
Carácterísticas activas en Reportes

### ISSUE THREAD

**Issue by diegocrzt** [TEDICpy/miciudad2#34]
Tiene sentido el uso de las siguientes características en los reportes ciudadanos

- Firmas (votos)
- Encuentros (meetups)
- Páginas

**Comment by diegocrzt** [comment]
Adjunto un issues actual al firmar reportes

application-6bd134ef14a9774b8eb967b6943905ac3e2c349a1548af576cab69060eacb8bf.js:1 POST https://beta.encarnacion.org.py/denuncias/i-6/denuncia_vote 500 (Internal Server Error)
t.ajax @ application-6bd134ef14a9774b8eb967b6943905ac3e2c349a1548af576cab69060eacb8bf.js:1
t.handleRemote @ application-6bd134ef14a9774b8eb967b6943905ac3e2c349a1548af576cab69060eacb8bf.js:1
(anonymous) @ application-6bd134ef14a9774b8eb967b6943905ac3e2c349a1548af576cab69060eacb8bf.js:1

**Comment by lupa18** [comment]
Si entiendo bien la pregunta, si la funcionalidad existe, dejémosla. 

Si el problema es la eliminación del comité, entonces ¿no se podría solucionar dejando el comité pero requiriendo 0 firma?

**Comment by diegocrzt** [comment]
No sabemos si la funcionalidad es adecuada para lo que se quiere en reportes, como requerir que la gente firme reportes y o creen páginas.

El flujo se heredó de las iniciativas en donde el comité definía un periodo de recolección de firmas en fomra de votos, cuando este termina el reporte deja de estar activo y se cierra.

Tampoco sabemos si este periodo es necesario, y si el funcionamiento actual se adecuado para reportes.

**Comment by lupa18** [comment]
Si mal no recuerdo del TDR, la **votación** era transversal a todos los tipos de contenido. Ya lo de las páginas puede ser más prescindible.

**Comment by diegocrzt** [comment]
ok, entonces vamos a dejar el comité y el flujo va a ser igual al flujo de iniciativas, y se va a buscar una manera de requerir 0 firmas

**Comment by diegocrzt** [comment]
Se debe volver a probar Reportes para validar su flujo de trabajo
- No hay comité 
- Se requeiren cero firmas
- Y se simplifica la vista

**Comment by lupa18** [comment]
Estoy creando un reporte ahora y me pide "Tipo de firma" y me parece que no tiene sentido
