### ISSUE TITLE
Error al firmar un reporte

### ISSUE THREAD

**Issue by diegocrzt** [TEDICpy/miciudad2#36]
Adjunto un issues actual al firmar reportes, esto está relacionado a la eliminación de comité

application-6bd134ef14a9774b8eb967b6943905ac3e2c349a1548af576cab69060eacb8bf.js:1 POST https://beta.encarnacion.org.py/denuncias/i-6/denuncia_vote 500 (Internal Server Error)
t.ajax @ application-6bd134ef14a9774b8eb967b6943905ac3e2c349a1548af576cab69060eacb8bf.js:1
t.handleRemote @ application-6bd134ef14a9774b8eb967b6943905ac3e2c349a1548af576cab69060eacb8bf.js:1
(anonymous) @ application-6bd134ef14a9774b8eb967b6943905ac3e2c349a1548af576cab69060eacb8bf.js:1

**Comment by lupa18** [comment]
Hablamos de verificar sin en vez de eliminar comité se pone firmas requeridas = 0

**Comment by diegocrzt** [comment]
Los problemas relacionados al inflector, el comité y la candiad de firmas requeridas estan resultos, pero queda pendiente la validación correcta del flujo de trabajo para esta funcionalidad
