### ISSUE TITLE
La imagen de la portada afecta el tiempo de respuesta

### ISSUE THREAD

**Issue by diegocrzt** [TEDICpy/miciudad2#37]
El tamaño de la imagen de portada hace que la carga de la página se enlentezca

**Comment by lupa18** [comment]
El enlace no me lleva a nada. De todos modos ¿a cuál imagen se refiere este issue?

**Comment by diegocrzt** [comment]
Se refería a cada imagen que se mostraba en la página de inicio, estas son sus versiones comprimidas, las dejo acá para considerarlas

![bannernuevo-02](https://user-images.githubusercontent.com/6553005/41123915-447a4110-6a6e-11e8-82aa-fe77e33b696c.jpg)

![foto](https://user-images.githubusercontent.com/6553005/41123948-62af3820-6a6e-11e8-8d0b-07121936bf17.jpg)

![icon1-919c2a16eabaad4dbaf1554db0fcfc6a220e0f844420](https://user-images.githubusercontent.com/6553005/41123955-65647b0c-6a6e-11e8-8d1f-833bdd4afd94.png)

![icon2-63f64c6fc86a9e89944dcabe1ba0ef9b866ca3ce2ea4](https://user-images.githubusercontent.com/6553005/41123959-68cb5bb2-6a6e-11e8-988b-ca7d4ecce441.png)

![icon3-6620ef80e68a951fa476a72d9deb46648b36b1a1fbc3](https://user-images.githubusercontent.com/6553005/41123961-6b4938dc-6a6e-11e8-88d7-8433b0e10ecc.png)

![medium_logo-horizontal](https://user-images.githubusercontent.com/6553005/41123966-70240666-6a6e-11e8-8aaa-ba6e811adc55.png)

**Comment by yank07** [comment]
Listo la optimizacion de las imagenes estaticas, para las imagenes que se cargan a traves del panel de admin, deberian de ser en formato jpg y con compresion del 60% para reducir el tamaño.

**Comment by diegocrzt** [comment]
Se configuró al compresión en apache para soportar todos los assets que usa la aplicación
