### ISSUE TITLE
Términos y condiciones

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/miciudad2#4]
Los términos y condiciones deberían tener su url en español: https://beta.encarnacion.org.py/pages/terminos-y-condiciones. Supongo con el slug será suficiente: terminos-y-condiciones 

La página está creada, pero el sistema debería apuntar allí. 

Adjunto imagen que me pasó Diego:

![20180510212425_nforce680i](https://user-images.githubusercontent.com/463429/39946095-3d8f53e4-5543-11e8-9aa5-dcd5c5fdfbd0.png)

**Comment by diegocrzt** [comment]
Debido a esta incidencia en upstream https://github.com/decidim/decidim/issues/3374.

Además de cambiar el slug, se debe fijar la versión de `high-voltage` (una dependencia) para que funcionen corretamente las páginas, este fue un cambio reciente en upstream.

**Comment by diegocrzt** [comment]
https://beta.encarnacion.org.py/pages/terminos-y-condiciones

![20180517220600_nforce680i](https://user-images.githubusercontent.com/6553005/40212562-90b8630a-5a1e-11e8-8804-b8f7a0589eb1.png)

**Comment by lupa18** [comment]
Andando
