### ISSUE TITLE
Inconsistencia y/o errores de visualización en portada

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/miciudad2#40]
En portada en la parte de estadísticas abajo dice que hay 4 iniciativas y 3 reportes. 

Sin embargo no aparecen listadas en portada. 

A su vez tampoco aparecen en sus respectivas páginas: 

* https://beta.encarnacion.org.py/initiatives
* https://beta.encarnacion.org.py/denuncias (ver: https://github.com/TEDICpy/decidim-reportes/issues/6)

Por su parte la cantidad de **eventos** no aparece en la sección estadísticas.

**Comment by diegocrzt** [comment]
Lo que suceda acá es que decidim lista por defecto en la portada y el listado principal las iniciativas que tienen fecha de recogida de firma mayor al día de hoy, o que todavía no tengan la cantidad de votos para ser aprobadas. A esto le llaman Iniciativas `Abiertas`. Lo mismo ocurre con los reportes por que heredan ese comportamiento de iniciativas.

Esto es así en decidim core también, el listado permite usar el filtro por `Estados` para ver las iniciativas que ya estan `Cerradas`(`Aprobadas`, o `Expiradas`)

![20180613230045_m4800](https://user-images.githubusercontent.com/6553005/41389240-a4b61524-6f5d-11e8-9c9a-3a4bf9c5bb6f.png)

Por qué el equipo de decidim decidió este enfoque no es claro para mí, pero el mismo comportamiento se replica en casi todos sus listados.

**Comment by lupa18** [comment]
Bueno, vuelvo sobre esto: 

Si hay un comportamiento que se cumple para 2 tipos de contenido, debería cumplirse para los 3, por lo que eventos debería funcionar igual. 

- Ahora mismo hay 6 eventos (que además se muestran superpuestos) y uno "activo" pero las estadísticas dice 1. 

Además se ve raro un texto que dice, "encuentros 3":
 
![seleccion_585](https://user-images.githubusercontent.com/463429/42108557-47c93dd6-7bb1-11e8-8b19-c820068332fc.png)
