### ISSUE TITLE
Al registrarse no llegan los correos

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/miciudad2#5]
**Comportamiento esperado:** 

Al registrar un nuevo usuario debería llegar un correo de confirmación

**Comportamiento observado:**

El sistema indica: "Se ha enviado un mensaje con un enlace de confirmación a tu correo electrónico. Abre el enlace para activar tu cuenta."

Sin embargo **el correo no llega**. 

**Pasos para reproducirlo:**
1. Ir a registro de usuario: https://beta.encarnacion.org.py/users/sign_up
2. Crear nuevo usuario y hacer clic en registrarse

**Comment by diegocrzt** [comment]
En una actualización modifiqué involuntariamente las credenciales del smtp, está ahora corregido y ahora los correos deberían llegar ya, favor verificar

**Comment by lupa18** [comment]
Perfecto. Ya llegan.
