### ISSUE TITLE
Error en enlace de página términos y condiciones

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/miciudad2#58]
El menú principal te lleva a un enlace que no existe: 

https://www.encarnacion.org.py/admin/static_pages/https:%2F%2Fwww.encarnacion.org.py%2Fpages%2Fterminos-y-condiciones/edit

**Comment by bauerpy** [comment]
participa -> faq
registrate -> https://www.encarnacion.org.py/users/sign_up
cambiar en base de datos las url de las paginas staticas
