### ISSUE TITLE
Iniciativas publicadas deberían verse en portada

### ISSUE THREAD

**Issue by lupa18** [TEDICpy/miciudad2#6]
**Comportamiento esperado:**

Como hay al menos una iniciativa en portada, esta debería verse en portada. 

Además debería verse en la sección de estadísticas.

**Comportamiento observado:**

No aparece ninguna iniciativa en portada.

**Pasos para reproducirlo:**
1. Tener alguna iniciativa publicada (ver captura 1)
2. Ir a portada y comprobar que no hay nada (ver captura 2)
3. La sección de estadísticas tampoco muestra nada (ver captura 3)

Captura 1:
![seleccion_517](https://user-images.githubusercontent.com/463429/40060403-df0c0e92-582c-11e8-9a9a-0b44fa3f2e91.png)

Captura 2:
![portada](https://user-images.githubusercontent.com/463429/40060485-237fd45a-582d-11e8-96f2-313101be0047.png)

Captura 3:

![seleccion_518](https://user-images.githubusercontent.com/463429/40060887-fccc2f2e-582d-11e8-93a7-c6d0da04c603.png)

**Comment by diegocrzt** [comment]
La portada ahora muestra las iniciativas antes que cualquier proceso participativo

![20180518171447_nforce680i](https://user-images.githubusercontent.com/6553005/40258288-13e65700-5abf-11e8-9977-3364a6cb3809.png)

Y las estadísticas ya reflejan el conteo de iniciatias publicadas

![20180518171457_nforce680i](https://user-images.githubusercontent.com/6553005/40258307-238c5a4c-5abf-11e8-9527-6bc47fdc5919.png)

**Comment by diegocrzt** [comment]
Estos cambios fueron introducidos en el PR #9

**Comment by lupa18** [comment]
y cómo se puede lograr que tenga un "thumbnail" o imagen asociada?

**Comment by diegocrzt** [comment]
Ahora las iniciativas al crearse requieren una imagen que se usa a modo de thumnail en el listado de iniciatvias de la página principal

![20180606194844_m4800](https://user-images.githubusercontent.com/6553005/41070815-cae3e5fa-69c2-11e8-823a-1852554c7e90.png)

**Comment by yank07** [comment]
@lupa18  podes pedirle al diseñador que nos ayude de mejorar esa parte?

**Comment by lupa18** [comment]
Necesito poder ver iniciativas para pedirle
ahora mismo hay dos pero no estoy pudiendo firmarlas

**Comment by lupa18** [comment]
Seguimos en https://github.com/TEDICpy/decidim-initiatives/issues/12
